
package com.cxf.soap.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Operations", targetNamespace = "http://ws.soap.cxf.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Operations {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "add", targetNamespace = "http://ws.soap.cxf.com/", className = "com.cxf.soap.ws.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://ws.soap.cxf.com/", className = "com.cxf.soap.ws.AddResponse")
    public int add(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sub", targetNamespace = "http://ws.soap.cxf.com/", className = "com.cxf.soap.ws.Sub")
    @ResponseWrapper(localName = "subResponse", targetNamespace = "http://ws.soap.cxf.com/", className = "com.cxf.soap.ws.SubResponse")
    public int sub(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

}
