
package com.cxf.soap.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "OperationsImplService", targetNamespace = "http://ws.soap.cxf.com/", wsdlLocation = "http://localhost:8089/apache-cxf-soap-ws-provider/services/op?wsdl")
public class OperationsImplService
    extends Service
{

    private final static URL OPERATIONSIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException OPERATIONSIMPLSERVICE_EXCEPTION;
    private final static QName OPERATIONSIMPLSERVICE_QNAME = new QName("http://ws.soap.cxf.com/", "OperationsImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8089/apache-cxf-soap-ws-provider/services/op?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        OPERATIONSIMPLSERVICE_WSDL_LOCATION = url;
        OPERATIONSIMPLSERVICE_EXCEPTION = e;
    }

    public OperationsImplService() {
        super(__getWsdlLocation(), OPERATIONSIMPLSERVICE_QNAME);
    }

    public OperationsImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), OPERATIONSIMPLSERVICE_QNAME, features);
    }

    public OperationsImplService(URL wsdlLocation) {
        super(wsdlLocation, OPERATIONSIMPLSERVICE_QNAME);
    }

    public OperationsImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, OPERATIONSIMPLSERVICE_QNAME, features);
    }

    public OperationsImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OperationsImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Operations
     */
    @WebEndpoint(name = "OperationsImplPort")
    public Operations getOperationsImplPort() {
        return super.getPort(new QName("http://ws.soap.cxf.com/", "OperationsImplPort"), Operations.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Operations
     */
    @WebEndpoint(name = "OperationsImplPort")
    public Operations getOperationsImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.soap.cxf.com/", "OperationsImplPort"), Operations.class, features);
    }

    private static URL __getWsdlLocation() {
        if (OPERATIONSIMPLSERVICE_EXCEPTION!= null) {
            throw OPERATIONSIMPLSERVICE_EXCEPTION;
        }
        return OPERATIONSIMPLSERVICE_WSDL_LOCATION;
    }

}
